#+STARTUP: content logdone hideblocks
#+TODO: TASK(t!) | DONE(d) CANCEL(c)
#+TODO: BUG(b!) | FIXED(f) REJECT(r)
#+PRIORITIES: A F C
#+TAGS: current(c) testing(t)
#+CONSTANTS: last_issue_id=4

* Задачи
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив задач
  :END:

** TASK Сделать экранирование повторов символов в сообщении
   :PROPERTIES:
   :issue_id: 4
   :issue_type: task
   :END:

   [2018-03-16 Пт]

   Нужно отыскивать все повторы символов от четырёх и выше и заменять
   их в тексте с конца (из-за особенностей работы регулярных выражений
   в распространённых библиотеках). Нужно также учесть, что длинные
   фразы из разных символов тоже считаются повторами.

   Часто в тексте несколько повторов надо сделать, неудобно их один за
   одним делать. Удобнее быстро вставить текст и быстро получить
   текст. Поэтому однострочное поле для ввода текста не подходит.

   [2018-03-20 Вт]

   При исследовании оказалось, что повторы одного символа и повторы
   группы символов обрабатываются по-разному. Один символ сжимается,
   начиная с четырёх повторов, а группа символов сжимается, начиная с
   двух повторов. Видимо, там разные алгоритмы как поиска, так и
   замены.

   Решил пока сделать экранирование только для повторов одного
   символа.


* Баги
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив багов
  :END:


* Окружение
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив окружения
  :END:

** TASK Сделать настройку порта при сборке проекта
   :PROPERTIES:
   :issue_id: 1
   :issue_type: task
   :END:

   [2017-10-24 Вт]

   Сейчас ставится порт 5080 без возможности его изменить. Этот порт
   может быть занят или просто нужен другой порт.

   В configure нужно сделать возможность смены порта.

** TASK Сделать сборку веб-версии
   :PROPERTIES:
   :issue_id: 2
   :issue_type: task
   :END:

   [2017-10-24 Вт]

   Может понадобиться выгружать приложение в Интернет. В таком случае
   не нужно делать системный скрипт и файл для регистрации службы в
   systemd.

   Должна быть возможность построить приложение для копирования в сеть
   без лишних файлов.
