#+STARTUP: content hideblocks
#+TODO: TASK(t!) | DONE(d) CANCEL(c)
#+TODO: BUG(b!) | FIXED(f) REJECT(r)

* Архив задач

** DONE Сделать экранирование повторов символов в сообщении
   CLOSED: [2018-03-29 Чт 20:30]
   :PROPERTIES:
   :issue_id: 4
   :issue_type: task
   :ARCHIVE_TIME: 2018-03-29 Чт 20:31
   :ARCHIVE_FILE: ~/prog/projects/python/lowes/tasks/tasks.org
   :ARCHIVE_OLPATH: Задачи
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2018-03-16 Пт]

   Нужно отыскивать все повторы символов от четырёх и выше и заменять
   их в тексте с конца (из-за особенностей работы регулярных выражений
   в распространённых библиотеках). Нужно также учесть, что длинные
   фразы из разных символов тоже считаются повторами.

   Часто в тексте несколько повторов надо сделать, неудобно их один за
   одним делать. Удобнее быстро вставить текст и быстро получить
   текст. Поэтому однострочное поле для ввода текста не подходит.

   [2018-03-20 Вт]

   При исследовании оказалось, что повторы одного символа и повторы
   группы символов обрабатываются по-разному. Один символ сжимается,
   начиная с четырёх повторов, а группа символов сжимается, начиная с
   двух повторов. Видимо, там разные алгоритмы как поиска, так и
   замены.

   Решил пока сделать экранирование только для повторов одного
   символа.


* Архив багов

* Архив окружения

** DONE Сделать поверхностные юнит-тесты
   CLOSED: [2017-11-05 Вс 13:07]
   :PROPERTIES:
   :issue_id: 3
   :issue_type: task
   :ARCHIVE_TIME: 2017-11-05 Вс 13:08
   :ARCHIVE_FILE: ~/prog/projects/python/lowes/tasks/tasks.org
   :ARCHIVE_OLPATH: Окружение
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2017-10-24 Вт]

   Сейчас юнит-тестов нет и нужно выяснить, с помощью чего их делают
   вообще. Для тестирования нужно многие локальные функции повыносить
   наружу, чтобы юнит-тесты могли иметь к ним доступ.
